name: 'Test Action'
description: 'Test'
author: 'test'
runs:
  using: "composite"
  steps: 
    - run: C:/thunderscan-cli/tsapiclient.exe --waitfinished --threshold high:1,medium:1,low:1 --local $pwd
      shell: cmd
    - run: echo "test123"
      shell: cmd
