name: 'Test Action'
description: 'Test'
author: 'test'
inputs:
  target:
    required: true
    description: 'Provide target'
    default: ''
  api_token:
    required: true
    description: 'Provide API token'
    default: ''
runs:
  using: "composite"
  steps: 
    - run: C:/thunderscan-cli/tsapiclient.exe --waitfinished --threshold high:1,medium:1,low:1 --local ${{ inputs.target }}
      shell: powershell
    - run: echo "test123"
      shell: cmd
  env:
    API_TOKEN: "${{ inputs.api_token }}"
