name: 'Test Action'
description: 'Test'
author: 'test'
inputs:
  api_key:
    required: true
    description: 'Provide ThunderScan API key'
    default: ''
runs:
  using: "composite"
    steps: 
      run: C:/thunderscan-cli/tsapiclient.exe --waitfinished --threshold high:1,medium:1,low:1 --local $pwd
  env:
    API_URL: "${{ inputs.api_key }}"
      
